export const APP_CONFIG = {
  GA_ID: "G-1TWP6S7S8H",
  DEFAULT_FREQUENCY: 30,
  DEFAULT_MAX_TILT: 20,
  DEFAULT_FONT_SIZE: "text-base",
  DEFAULT_LANGUAGE: "zh" as const,
  ANIMATION_DURATION: 1000,
}

export const TEXTS = {
  zh: {
    settings: "设置",
    frequency: "摆动频率 (秒)",
    frequencyHint: "建议范围：5-300秒",
    maxTiltAngle: "最大倾斜角度 (度)",
    maxTiltAngleHint: "建议范围：5-45度",
    showStatus: "显示状态信息",
    showStatusHint: "显示倾斜角度和倒计时信息",
    fontSize: "字体大小",
    fontSizeHint: "调整新闻文字大小",
    small: "小",
    medium: "中",
    large: "大",
    dataSourceSettings: "数据源设置",
    addNewSource: "添加新数据源",
    sourceName: "数据源名称",
    sourceUrl: "JSON数据链接",
    addSource: "添加数据源",
    loading: "正在加载新闻...",
    loadError: "无法加载新闻内容，请检查网络连接",
    tiltAngle: "倾斜角度",
    nextTilt: "下次摆动",
    seconds: "秒",
    language: "语言",
    languageHint: "选择界面语言",
    dailyNews: "每日新闻",
    adSettings: "广告设置",
    showAds: "显示广告",
    showAdsHint: "在页面两侧显示广告区域",
    githubRepo: "GitHub 仓库",
    signIn: "登录",
    signOut: "登出",
    account: "账户",
    syncHint: "登录后可同步设置到云端",
  },
  en: {
    settings: "Settings",
    frequency: "Frequency (seconds)",
    frequencyHint: "Recommended range: 5-300 seconds",
    maxTiltAngle: "Max Tilt Angle (degrees)",
    maxTiltAngleHint: "Recommended range: 5-45 degrees",
    showStatus: "Show Status Info",
    showStatusHint: "Display tilt angle and countdown",
    fontSize: "Font Size",
    fontSizeHint: "Adjust news text size",
    small: "Small",
    medium: "Medium",
    large: "Large",
    dataSourceSettings: "Data Source Settings",
    addNewSource: "Add New Data Source",
    sourceName: "Source Name",
    sourceUrl: "JSON Data URL",
    addSource: "Add Source",
    loading: "Loading news...",
    loadError: "Unable to load news content, please check network connection",
    tiltAngle: "Tilt Angle",
    nextTilt: "Next Shaking",
    seconds: "s",
    language: "Language",
    languageHint: "Select interface language",
    dailyNews: "Daily News",
    adSettings: "Ad Settings",
    showAds: "Show Ads",
    showAdsHint: "Display ad areas on both sides of the page",
    githubRepo: "GitHub Repository",
    signIn: "Sign In",
    signOut: "Sign Out",
    account: "Account",
    syncHint: "Sign in to sync settings to cloud",
  },
} as const

export const DEFAULT_SOURCES = {
  zh: [
    {
      id: 1,
      name: "每日新闻",
      url: "https://news.ravelloh.top/latest.json",
      active: true,
    },
  ],
  en: [
    {
      id: 1,
      name: "Daily News",
      url: "https://api.rss2json.com/v1/api.json?rss_url=https://feeds.bbci.co.uk/news/rss.xml",
      active: true,
    },
  ],
}
